// Связь профессии (по id из data.js) с её профессиональным праздником
const profHolidays = {
    "civil-engineer": { name: "День строителя", date: "8 августа" },
    "architect-engineer": { name: "Всемирный день архитектора", date: "4 октября" },
    "road-engineer": { name: "День работников дорожного хозяйства", date: "18 октября" },
    "mechanical-engineer": { name: "День машиностроителя", date: "27 сентября" },
    "automotive-engineer": { name: "День работников автомобильного транспорта", date: "29 октября" },
    "power-engineer": { name: "День энергетика", date: "16 декабря" },
    "nuclear-engineer": { name: "День работников атомной промышленности", date: "30 сентября" },
    "aerospace-engineer": { name: "День авиации России", date: "19 августа" },
    "chemical-engineer": { name: "День химика", date: "30 мая" },
    "oil-gas-engineer": { name: "День работников нефтяной и газовой промышленности", date: "31 октября" },
    "metallurgical-engineer": { name: "День металлурга", date: "19 июля" },
    "materials-engineer": { name: "День ювелира", date: "31 января" },
    "mining-engineer": { name: "День шахтёра", date: "27 августа" },
    "environmental-engineer": { name: "День эколога", date: "5 июня" },
    "biomedical-engineer": { name: "День медицинского работника", date: "16 июня" },
    "robotics-engineer": { name: "День робототехники", date: "7 февраля" },
    "railway-engineer": { name: "День железнодорожника", date: "2 августа" },
    "shipbuilding-engineer": { name: "День кораблестроителя", date: "29 июня" },
    "instrumentation-engineer": { name: "Всемирный день метрологии", date: "20 мая" },
    "telecom-engineer": { name: "День радио", date: "7 мая" },
    "food-engineer": { name: "День работников пищевой промышленности", date: "18 октября" },
    "textile-engineer": { name: "День работников лёгкой промышленности", date: "20 октября" },
    "forest-engineer": { name: "День работников леса", date: "17 сентября" },
    "water-engineer": { name: "Всемирный день водных ресурсов", date: "22 марта" },
    "lighting-engineer": { name: "Международный день света", date: "16 мая" },
    "data-engineer": { name: "День программиста", date: "14 сентября" },
    "devops-engineer": { name: "День программиста", date: "14 сентября" },
    "ml-engineer": { name: "День программиста", date: "14 сентября" },
    "security-engineer": { name: "День компьютерщика", date: "14 февраля" },
    "cloud-engineer": { name: "День программиста", date: "14 сентября" },
    "embedded-engineer": { name: "День программиста", date: "14 сентября" },
    "frontend-engineer": { name: "День программиста", date: "14 сентября" },
    "backend-engineer": { name: "День программиста", date: "14 сентября" },
    "qa-engineer": { name: "День тестировщика", date: "9 сентября" },
    "mobile-engineer": { name: "День программиста", date: "14 сентября" },
    "military-engineer": { name: "День инженерных войск РФ", date: "21 января" },
    "polygraph-engineer": { name: "День российской печати", date: "13 января" },
    "civil-defense-engineer": { name: "Всемирный день гражданской обороны", date: "1 марта" },
    "geodetic-engineer": { name: "День геодезии и картографии", date: "5 марта" },
    "astronomer-engineer": { name: "День астрономии", date: "3 ноября" },
    "restoration-engineer": { name: "Международный день охраны памятников и исторических мест", date: "18 апреля" },
    "standardization-engineer": { name: "Всемирный день стандартизации", date: "15 октября" },
    "patent-engineer": { name: "День изобретателя и рационализатора", date: "24 июня" },
    "space-engineer": { name: "День Космических войск", date: "4 октября" }
};